### ISSUE TITLE
document junit.xml

### ISSUE THREAD

**Issue by markhu** [zatosource/zato-apitest#47]
There is a brief mention in the README that it "Can be integrated with JUnit" ...but no substantiating docs or examples. I'm primarily interested in learning how to get the test results published in junit.xml format both with Maven, and independently.

**Comment by dsuch** [comment]
Hello @markhu,

the underlying engine to run all the tests is [behave](https://pythonhosted.org/behave/index.html) - it's a Python-based tool on top of which all zato-apitest steps run on.

In particular, when you open the config.ini file in your zato-apitest project's directory, you will find lines such as here:

```ini
[behave]
options=--format pretty --no-source --no-timings
```

These are command line options that are provided to behave as they are. Now, we can add ```--junit --junit-directory=/tmp/my-directory``` so that it reads:

```ini
[behave]
options=--format pretty --no-source --no-timings --junit --junit-directory=/tmp/my-directory
```

And now the XML output will be in /tmp/my-directory.

All the other options that behave honours are documented here: https://pythonhosted.org/behave/behave.html

Please let me know if that helps.

Regards.

**Comment by dsuch** [comment]
Mass-closing old tickets.
